# Generated by Django 2.2 on 2021-08-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=60)),
                ('date', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
