# Generated by Django 2.2 on 2021-08-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0003_auto_20210807_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
