# Generated by Django 2.2 on 2021-08-07 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0005_auto_20210807_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
