# Generated by Django 2.2 on 2021-08-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0006_auto_20210807_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='period',
            field=models.BooleanField(default=False),
        ),
    ]
