# Generated by Django 2.2 on 2021-08-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0008_auto_20210813_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='period',
            field=models.BooleanField(default=False),
        ),
    ]
